### ISSUE TITLE
"Installing and using Charm" doesn't tell how to run files, only REPL

### ISSUE THREAD

**Issue by gavr123456789** [tim-hardcastle/Charm#4]
> You now have a working copy of Charm which can be run with .\charm ... This is a REPL.  
  
And when trying to compile\run file: 
```bash
 ./charm examples/bar.ch

  ╔══════════♥══════════╗
  ║ Charm version 0.4.0 ║
  ╚══════════♥══════════╝


Hub error: attempt to access the value of a private or non-existent variable or
constant 'examples'
```

**Comment by tim-hardcastle** [comment]
I'll clarify that. At present you're meant to run things from inside Charm; you start it up and then type hub run "examples/bar.ch. I'll have to think about what you should be able to do from the command line. Should it execute commands, so that ./charm hub run "examples/bar.ch" does what you want? Or should it execute hub commands, so that ./charm run "examples/bar.ch" does what you want? Or should it look for filenames as a first default to whatever else it does, so that ./charm examples/bar.ch does what you want? I will think about this.
